# Generated by Django 4.0.1 on 2022-03-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('release_year', models.IntegerField(default=0)),
                ('reg_number', models.CharField(max_length=10)),
                ('carrying', models.FloatField()),
            ],
        ),
    ]
