# Generated by Django 4.0.1 on 2022-03-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('release_year', models.IntegerField(default=0)),
                ('reg_number', models.CharField(max_length=10)),
                ('trailer_type', models.CharField(max_length=20)),
                ('carrying', models.FloatField()),
                ('info', models.CharField(max_length=500, null=True)),
                ('transport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailers', to='transportation.transport')),
            ],
        ),
    ]
