# Generated by Django 4.0.1 on 2022-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
