# Generated by Django 4.0.1 on 2022-03-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_trucktrailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateField()),
                ('phone_num', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('transport', models.ManyToManyField(related_name='drivers', to='transportation.Transport')),
            ],
        ),
    ]
