# Generated by Django 4.0.1 on 2022-03-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('cargo', models.CharField(max_length=500)),
                ('weight', models.FloatField(default=0.0)),
                ('shipper', models.CharField(max_length=300)),
                ('consignee', models.CharField(max_length=300)),
                ('load_place', models.CharField(max_length=300)),
                ('unload_place', models.CharField(max_length=300)),
                ('rates', models.FloatField(default=0.0)),
                ('tax', models.BooleanField(default=False)),
                ('loading_date', models.DateField()),
                ('unloading_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('info', models.CharField(max_length=500, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dr_orders', to='transportation.driver')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tr_orders', to='transportation.transport')),
            ],
        ),
    ]
